# Generated by Django 4.2.3 on 2025-01-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="url",
        ),
    ]
