# Generated by Django 4.2.17 on 2025-01-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="time",
            field=models.IntegerField(
                help_text="Time for quiz", null=True, verbose_name="Time"
            ),
        ),
    ]
