# Generated by Django 4.2.17 on 2025-01-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_quiz_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ManyToManyField(
                blank=True,
                related_name="questions",
                to="myapp.quiz",
                verbose_name="Quiz",
            ),
        ),
    ]
