# Generated by Django 4.2.17 on 2025-01-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_question_quiz_question_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ManyToManyField(
                blank=True, to="myapp.quiz", verbose_name="Quiz"
            ),
        ),
    ]
