# Generated by Django 4.2.17 on 2025-01-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizs",
                to="myapp.subcategory",
                verbose_name="SubCategory",
            ),
        ),
    ]
